[extension]
id = "graphix"
name = "Graphix"
description = "Language support for the Graphix dataflow programming language"
version = "0.1.0"
schema_version = 1
authors = ["Graphix Authors"]
repository = "https://github.com/graphix-lang/graphix"

[grammars.graphix]
repository = "https://github.com/graphix-lang/graphix"
path = "ide/tree-sitter-graphix"

[language_servers.graphix-lsp]
name = "Graphix Language Server"
languages = ["Graphix"]
